import {defineType, defineField} from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: 'Αρχική σελίδα',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero'},
    {name: 'audience', title: 'Για ποιον είναι'},
    {name: 'problem', title: 'Πρόβλημα'},
    {name: 'features', title: 'Λειτουργίες'},
    {name: 'stats', title: 'Στατιστικά'},
    {name: 'brand', title: 'White-label'},
    {name: 'security', title: 'Ασφάλεια'},
    {name: 'pricing', title: 'Τιμές'},
    {name: 'founding', title: 'Ιδρυτικοί'},
    {name: 'contact', title: 'Φόρμα'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'heroBadge', title: 'Eyebrow', type: 'string', group: 'hero'}),
    defineField({name: 'heroTitle', title: 'Headline', type: 'text', rows: 3, group: 'hero'}),
    defineField({name: 'heroDescription', title: 'Υπότιτλος', type: 'text', rows: 4, group: 'hero'}),
    defineField({name: 'heroPrimaryCta', title: 'Κύριο CTA', type: 'string', group: 'hero'}),
    defineField({name: 'heroSecondaryCta', title: 'Δευτερεύον CTA', type: 'string', group: 'hero'}),
    defineField({name: 'heroTrustLine', title: 'Σημείωση εμπιστοσύνης', type: 'string', group: 'hero'}),
    defineField({name: 'heroMockupCollection', title: 'Mockup συλλογή', type: 'string', group: 'hero'}),

    defineField({name: 'audienceEyebrow', title: 'Eyebrow', type: 'string', group: 'audience'}),
    defineField({name: 'audienceTitle', title: 'Headline', type: 'text', rows: 2, group: 'audience'}),
    defineField({
      name: 'audienceCards',
      title: 'Segments (πρώτο = lead dark card)',
      type: 'array',
      of: [{type: 'iconCard'}],
      group: 'audience',
    }),

    defineField({name: 'problemEyebrow', title: 'Eyebrow', type: 'string', group: 'problem'}),
    defineField({name: 'problemTitle', title: 'Headline', type: 'string', group: 'problem'}),
    defineField({
      name: 'problemCards',
      title: 'Κάρτες προβλήματος',
      type: 'array',
      of: [{type: 'iconCard'}],
      group: 'problem',
    }),
    defineField({name: 'beforeTitle', title: 'Τίτλος «Πριν»', type: 'string', group: 'problem'}),
    defineField({
      name: 'beforeSteps',
      title: 'Βήματα «Πριν»',
      type: 'array',
      of: [{type: 'string'}],
      group: 'problem',
    }),
    defineField({name: 'beforeFootnote', title: 'Υποσημείωση «Πριν»', type: 'string', group: 'problem'}),
    defineField({name: 'afterTitle', title: 'Τίτλος «Μετά»', type: 'string', group: 'problem'}),
    defineField({
      name: 'afterSteps',
      title: 'Βήματα «Μετά»',
      type: 'array',
      of: [{type: 'string'}],
      group: 'problem',
    }),
    defineField({name: 'afterFootnote', title: 'Υποσημείωση «Μετά»', type: 'string', group: 'problem'}),

    defineField({name: 'featuresEyebrow', title: 'Eyebrow', type: 'string', group: 'features'}),
    defineField({name: 'featuresTitle', title: 'Headline', type: 'text', rows: 2, group: 'features'}),
    defineField({
      name: 'features',
      title: 'Λειτουργίες',
      type: 'array',
      of: [{type: 'featureItem'}],
      group: 'features',
    }),

    defineField({name: 'statEyebrow', title: 'Eyebrow', type: 'string', group: 'stats'}),
    defineField({name: 'statLabel', title: 'Headline ενότητας', type: 'string', group: 'stats'}),
    defineField({name: 'statValue', title: 'Μεγάλος αριθμός', type: 'string', group: 'stats'}),
    defineField({
      name: 'statBigNumberLabel',
      title: 'Ετικέτα κάτω από τον αριθμό',
      type: 'string',
      group: 'stats',
    }),
    defineField({name: 'statMoneyValue', title: 'Αξία σε χρήμα', type: 'string', group: 'stats'}),
    defineField({name: 'statDescription', title: 'Περιγραφή', type: 'text', rows: 4, group: 'stats'}),
    defineField({
      name: 'statBreakdown',
      title: 'Ανάλυση ωρών',
      type: 'array',
      group: 'stats',
      of: [
        {
          type: 'object',
          name: 'statBreakdownRow',
          fields: [
            defineField({name: 'label', title: 'Ετικέτα', type: 'string'}),
            defineField({name: 'hours', title: 'Ώρες', type: 'number'}),
            defineField({name: 'hoursLabel', title: 'Εμφάνιση (π.χ. ~35ω)', type: 'string'}),
            defineField({name: 'percentOfMax', title: 'Ποσοστό μπάρας (0-100)', type: 'number'}),
          ],
          preview: {select: {title: 'label', subtitle: 'hoursLabel'}},
        },
      ],
    }),
    defineField({name: 'statDisclaimer', title: 'Υποσημείωση', type: 'text', rows: 2, group: 'stats'}),

    defineField({name: 'whiteLabelEyebrow', title: 'Eyebrow', type: 'string', group: 'brand'}),
    defineField({name: 'whiteLabelTitle', title: 'Headline', type: 'string', group: 'brand'}),
    defineField({
      name: 'whiteLabelDescription',
      title: 'Περιγραφή',
      type: 'text',
      rows: 4,
      group: 'brand',
    }),

    defineField({name: 'securityEyebrow', title: 'Eyebrow', type: 'string', group: 'security'}),
    defineField({name: 'securityTitle', title: 'Headline', type: 'string', group: 'security'}),
    defineField({
      name: 'securityItems',
      title: 'Σημεία ασφαλείας',
      type: 'array',
      of: [{type: 'iconCard'}],
      group: 'security',
    }),

    defineField({name: 'pricingEyebrow', title: 'Eyebrow', type: 'string', group: 'pricing'}),
    defineField({name: 'pricingTitle', title: 'Headline', type: 'string', group: 'pricing'}),
    defineField({
      name: 'pricingPlans',
      title: 'Πακέτα',
      type: 'array',
      of: [{type: 'pricingPlan'}],
      group: 'pricing',
    }),

    defineField({name: 'foundingEyebrow', title: 'Eyebrow', type: 'string', group: 'founding'}),
    defineField({name: 'foundingTitle', title: 'Headline', type: 'string', group: 'founding'}),
    defineField({
      name: 'foundingDescription',
      title: 'Περιγραφή',
      type: 'text',
      rows: 4,
      group: 'founding',
    }),

    defineField({name: 'contactTitle', title: 'Headline', type: 'string', group: 'contact'}),
    defineField({
      name: 'contactDescription',
      title: 'Περιγραφή',
      type: 'text',
      rows: 3,
      group: 'contact',
    }),
    defineField({
      name: 'contactConsentText',
      title: 'Κείμενο συναίνεσης',
      type: 'text',
      rows: 2,
      group: 'contact',
    }),
    defineField({
      name: 'contactSuccessMessage',
      title: 'Μήνυμα επιτυχίας',
      type: 'string',
      group: 'contact',
    }),
    defineField({
      name: 'contactSuccessTitle',
      title: 'Τίτλος επιτυχίας (παλιό)',
      type: 'string',
      group: 'contact',
      hidden: true,
    }),
    defineField({
      name: 'contactSuccessDescription',
      title: 'Περιγραφή επιτυχίας (παλιό)',
      type: 'text',
      rows: 2,
      group: 'contact',
      hidden: true,
    }),

    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'seo'}),
  ],
  preview: {prepare: () => ({title: 'Αρχική σελίδα'})},
})
